### ISSUE TITLE
Cannot create a list of a custom scalar type

### ISSUE THREAD

**Issue by schuma7** [prisma/nexus#114]
I'm using the PositiveInt scalar from the @okgrow/graphql-scalars package:

```javascript
const PositiveIntScalar = asNexusMethod(PositiveInt, 'positiveInt');
```
When trying to create a list of PositiveInt scalars using:
```javascript
t.list.positiveInt('editionNumbers');
```
It throws the following error:
```
TypeError: t.list.positiveInt is not a function
    at Object.definition (/Users/user/project/src/module/schema.ts:61:16)
    at SchemaBuilder.buildObjectType (/Users/user/project/node_modules/nexus/dist/builder.js:185:16)
    at SchemaBuilder.getOrBuildType (/Users/user/project/node_modules/nexus/dist/builder.js:540:29)
    at /Users/user/project/node_modules/nexus/dist/builder.js:127:45
    at Array.forEach (<anonymous>)
    at SchemaBuilder.getFinalTypeMap (/Users/user/project/node_modules/nexus/dist/builder.js:118:42)
    at buildTypes (/Users/user/project/node_modules/nexus/dist/builder.js:632:20)
    at makeSchemaInternal (/Users/user/project/node_modules/nexus/dist/builder.js:661:19)
    at Object.makeSchema (/Users/user/project/node_modules/nexus/dist/builder.js:689:18)
    at Object.<anonymous> (/Users/user/project/src/schema.ts:31:24)
```

I'm currently using Nexus 0.11.6

**Comment by schuma7** [comment]
Anyone looking for a workaround, you can always resort to the basic form:

```javascript
t.list.field('editionNumbers', { type: 'PositiveInt' });
```

**Comment by tgriesser** [comment]
Ah good catch, will make sure this gets fixed.

**Comment by unmyke** [comment]
You can use t.list.positiveInt if you pass to makeSchema the config object with 'types' prop containing an array with PositiveIntScalar that stands before type used PositiveIntScalar.

**Comment by createvo** [comment]
Same issue for me using a custom scalarType. I put the scalarType at first position in types array config in makeSchema but it works only for single and not for lists.

**Comment by unmyke** [comment]
@createvo, I had "t.list.customScalar is not a function" error and resolve it similar example below:

```javascript
// schema/scalars/custom-1.js
import { scalarType } from 'nexus';

const CustomScalar1 = scalarType({
  name: "CustomScalar1",
  asNexusMethod: 'customScalar1',
  // scalar definition
})

export default CustomScalar1;
```

```javascript
// schema/scalars/custom-2.js
import { scalarType } from 'nexus';

const CustomScalar2 = scalarType({
  name: "CustomScalar2",
  asNexusMethod: 'customScalar2',
  // scalar definition
})

export default CustomScalar1;
```

```javascript
// schema/scalars/index

export { default as CustomScalar1 } from './custom-1';
export { default as CustomScalar2 } from './custom-2';
```

```javascript
// schema/type/custom-1.js
import { objectType } from 'nexus';

const CustomType1 = objectType({
  name: "CustomType1",
  definition(t) {
    t.int("id", { description: "Id of the Custom Type 1" });
    t.customScalar1("custom1");
  },
});

export default CustomType1;
```

```javascript
// schema/type/custom-2.js
import { objectType } from 'nexus';

const CustomType2 = objectType({
  name: "CustomType2",
  definition(t) {
    t.int("id", { description: "Id of the Custom Type 2" });
    t.customScalar2("custom2");
  },
});

export default CustomType1;
```

```javascript
// schema/scalars/index.js
import { makeSchema } from 'nexus';

export { default as CustomType1 } from './custom-1';
export { default as CustomType2 } from './custom-2';
```

```javascript
// schema/index.js
import * as scalars from './scalars';
import * as types from './types';

export default makeSchema({ types: [scalars, types] });
```

Do you use it like this?

**Comment by zeehjr** [comment]
Hello, I also have the same issue using nexus v0.11.7
When adding a custom scalar and assigning "asNexusMethod", I can use it like:
`t.myCustomScalar`
But I can't use it as:
`t.list.myCustomScalar`

The error is the same as above.

**Comment by tgriesser** [comment]
@zeehjr Can you try with the latest beta? The beta will become the official release quite soon.
