### ISSUE TITLE
githunt-api installation error

### ISSUE THREAD

**Issue by jlarmstrongiv** [prisma/nexus#184]
After running `yarn install`, I received this error.
```shell
error An unexpected error occurred: "https://codeload.github.com/apollographql/GitHunt-API/tar.gz/30cca2d38cc715be07f687b222fb49903c75dc1d: Request failed \"404 Not Found\"".
```

**Comment by jlarmstrongiv** [comment]
The GitHunt API seems to be deprecated
![image](https://user-images.githubusercontent.com/20903247/61256920-bb136e80-a73c-11e9-8fcc-b2dc7379cded.png)

**Comment by jlarmstrongiv** [comment]
Are there any other examples of nexus with vanilla JavaScript?

**Comment by mariobermudezjr** [comment]
I also get an error just after doing yarn examples

` yarn examples
yarn run v1.13.0
$ yarn link-examples && cd website && yarn gulp run-examples
$ cd website && yarn && yarn gulp link-examples
[1/4] 🔍  Resolving packages...
success Already up-to-date.
$ /Users/macbookpro/Desktop/learning/prisma/nexus/website/node_modules/.bin/gulp link-examples
[17:42:37] Requiring external module ts-node/register
[17:42:38] Using gulpfile ~/Desktop/learning/prisma/nexus/website/gulpfile.ts
[17:42:38] Starting 'link-examples'...

Linking ts-ast-reader
Linking star-wars
Linking kitchen-sink
Linking githunt-api
Linking apollo-fullstack
Linking ghost
Linking website
Finished linking ghost
Finished linking website
[17:42:40] 'link-examples' errored after 2.56 s
[17:42:40] Error: Command failed: yarn
warning package.json: No license field
warning @graphql-nexus/example-githunt-api: No license field
error An unexpected error occurred: "https://codeload.github.com/apollographql/GitHunt-API/tar.gz/30cca2d38cc715be07f687b222fb49903c75dc1d: Request failed \"404 Not Found\"".

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:189:13)
    at maybeClose (internal/child_process.js:970:16)
    at Socket.stream.socket.on (internal/child_process.js:389:11)
    at Socket.emit (events.js:189:13)
    at Pipe._handle.close (net.js:600:12)
Finished linking ts-ast-reader
Finished linking star-wars
Finished linking kitchen-sink
Finished linking apollo-fullstack
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
new-yosemite-sofware-2015:nexus macbookpro$ `

**Comment by jasonkuhrt** [comment]
> Are there any other examples of nexus with vanilla JavaScript?

https://github.com/prisma/prisma-examples/tree/prisma2/javascript `graphql-auth` & `graphql`

If anyone wants to open a PR to update the readme mentioning the api no longer works feel free.
