### ISSUE TITLE
Error: Could not find filtering argument

### ISSUE THREAD

**Issue by mazzaker** [prisma/nexus#187]
I do not see my fault :-(

Error:

```
[INFO] 12:35:01 Restarting: /Users/DC-BT/Documents/Projects/necom/server/src/api/Customer/Gift.ts has been modified
Using ts-node version 8.3.0, typescript version 3.5.2
Error: Could not find filtering argument for Gift.categories
    at NexusPrismaBuilder.argsForQueryOrModelField (/Users/DC-BT/Documents/Projects/necom/server/node_modules/@generated/nexus-prisma/index.js:444:23)
    at NexusPrismaBuilder.computeArgsFromField (/Users/DC-BT/Documents/Projects/necom/server/node_modules/@generated/nexus-prisma/index.js:434:25)
    at Object.acc.<computed> [as categories] (/Users/DC-BT/Documents/Projects/necom/server/node_modules/@generated/nexus-prisma/index.js:568:139)
    at Object.definition (/Users/DC-BT/Documents/Projects/necom/server/src/api/Customer/Gift.ts:13:17)
    at SchemaBuilder.walkOutputType (/Users/DC-BT/Documents/Projects/necom/server/node_modules/@prisma/nexus/src/builder.ts:1192:9)
    at SchemaBuilder.walkTypes (/Users/DC-BT/Documents/Projects/necom/server/node_modules/@prisma/nexus/src/builder.ts:456:16)
    at SchemaBuilder.getFinalTypeMap (/Users/DC-BT/Documents/Projects/necom/server/node_modules/@prisma/nexus/src/builder.ts:464:10)
    at buildTypes (/Users/DC-BT/Documents/Projects/necom/server/node_modules/@prisma/nexus/src/builder.ts:1313:18)
    at makeSchemaInternal (/Users/DC-BT/Documents/Projects/necom/server/node_modules/@prisma/nexus/src/builder.ts:1357:9)
    at Object.makeSchema (/Users/DC-BT/Documents/Projects/necom/server/node_modules/@prisma/nexus/src/builder.ts:1408:9)
[ERROR] 12:35:06 Error: Could not find filtering argument for Gift.categories
```

Gift.ts:
```
import { objectType } from 'nexus';
import { queries, QueryMethod } from './';

queries.push({ name: "Gift", methods: [QueryMethod.One, QueryMethod.Many] });

export const Gift = objectType({
    name: 'Gift',
    definition(t) {
        t.model.id()
        t.model.name()
        t.model.cost()
        t.model.path()
        t.model.categories({ 
            filtering: { id: true, name: true }
        })
    },
});
```

GifftCategory.ts:

```
import { objectType } from 'nexus';
import { queries, QueryMethod } from './';

queries.push({ name: "GiftCategory", methods: [QueryMethod.Many, QueryMethod.One] });

export const GiftCategory = objectType({
    name: 'GiftCategory',
    definition(t) {
        t.model.id()
        t.model.name()
        t.model.gifts()
    },
});
```

**Comment by jasonkuhrt** [comment]
Hey @mazzaker could you share a repro repo?

**Comment by Bjoernstjerne** [comment]
https://github.com/mazzaker/prismaNexus-187

**Comment by jasonkuhrt** [comment]
@mazzaker thanks!

**Comment by jasonkuhrt** [comment]
After digging, I found that if I change the following LOC in nexus-prisma in the generated nexus-prisma code then the error in this issue goes away:

[link](https://github.com/prisma/nexus-prisma/blob/b474860b27cc78eae073f70ec2b193a69a2bf052/src/nexus-prisma/NexusPrismaBuilder.ts#L195)

```ts
  protected argsForQueryOrModelField(
    prismaModelName: string,
    graphQLTypeName: string,
    field: DMMF.SchemaField,
    opts: NexusPrismaMethodParams
  ) {
    let args: DMMF.SchemaArg[] = [];

    if (opts.filtering) {
      const whereArg = field.args.find(
        a =>
          a.inputType.type === `${prismaModelName}WhereInput` &&    // <--- remove this
          a.name === 'where'
      );
```

In the repro provided by @mazzaker 

The filtering exposed in question is:

```ts
const User = objectType({
  name: "User",
  definition(t) {
    t.model.id();
    t.model.email();
    t.model.name();
    t.model.posts({ filtering: { id: true } });    // <-- here
  },
});
```



And at runtime it fails like:

```
Error: Could not find filtering argument for User.posts
```
Where the value of `prismaModelName` is `User` so that its looking for an input type name of `UserWhereInput`

Finally the value of `field: DMMF.SchemaField` is:

```js
{
  name: 'posts',
  args: [
    {
      name: 'where',
      inputType: {
        type: 'PostWhereInput',
        kind: 'object',
        isRequired: false,
        isList: false
      }
    },
    {
      name: 'orderBy',
      inputType: {
        isList: false,
        isRequired: false,
        type: 'PostOrderByInput',
        kind: 'object'
      }
    },
    {
      name: 'skip',
      inputType: { type: 'Int', kind: 'scalar', isRequired: false, isList: false }
    },
    {
      name: 'after',
      inputType: {
        type: 'String',
        kind: 'scalar',
        isRequired: false,
        isList: false
      }
    },
    {
      name: 'before',
      inputType: {
        type: 'String',
        kind: 'scalar',
        isRequired: false,
        isList: false
      }
    },
    {
      name: 'first',
      inputType: { type: 'Int', kind: 'scalar', isRequired: false, isList: false }
    },
    {
      name: 'last',
      inputType: { type: 'Int', kind: 'scalar', isRequired: false, isList: false }
    }
  ],
  outputType: { type: 'Post', kind: 'object', isRequired: false, isList: true }
}
```

Now, I cannot figure at first glance why the current `nexus-prisma` is searching for an input matching `UserWhereInput` on a field of `posts`. It makes sense to me that the type of `where` input on `User.posts` field is for... `Post` and hence `PostWhereInput`...

Therefore I currently think the issue is on the seeker side, not the result set side.

This is the first time I crack open the nexus-prisma codebase, so I'm not sure.

**Comment by jasonkuhrt** [comment]
I believe this is a `nexus-prisma` issue, not a `nexus` issue. Therefore I will transfer this to the `nexus-prisma` repo.
