### ISSUE TITLE
local development and testing for contributing

### ISSUE THREAD

**Issue by kandros** [prisma/nexus#62]
looking at the scripts of the root package.json looks like running `yarn dev` is enough to make everything work locally but unfortunately
```
"scripts": {
    "dev": "yarn link-examples && tsc -w",
    "test": "jest",
    "build": "tsc && prettier --write 'dist/**/*.ts'",
    "lint": "tslint -p tsconfig.json",
    "clean": "rm -rf dist",
    "format": "prettier --write 'src/**/*.ts'",
    "prepublish": "yarn clean && yarn lint && yarn build",
    "postpublish": "yarn upgrade-deps || echo 'Oops...'",
    "website": "cd website && yarn && yarn start",
    "examples": "yarn link-examples && cd website && yarn gulp run-examples",
    "deploy-site": "cd website && yarn && yarn gulp link-website && yarn build",
    "link-examples": "cd website && yarn && yarn gulp link-examples",
    "unlink-examples": "cd website && yarn && yarn gulp unlink-examples",
    "upgrade-deps": "cd website && yarn && yarn gulp upgrade-deps",
    "ts-ast-reader": "cd examples/ts-ast-reader && yarn start"
  }

```

```
➜  nexus git:(develop) yarn dev         
yarn run v1.13.0
$ yarn link-examples && tsc -w
$ cd website && yarn && yarn gulp link-examples
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
$ /Users/jaga/coding/nexus/website/node_modules/.bin/gulp link-examples
[16:26:52] Requiring external module ts-node/register
[16:26:53] Using gulpfile ~/coding/nexus/website/gulpfile.ts
[16:26:53] Starting 'link-examples'...

Linking ts-ast-reader
Linking star-wars
Linking kitchen-sink
Linking githunt-api
Linking apollo-fullstack
Linking ghost
Linking website
Finished linking website
[16:27:06] 'link-examples' errored after 13 s
[16:27:06] Error: Command failed: yarn
warning package.json: No license field
warning @graphql-nexus/ghost-example-api: No license field
error ghost@2.13.1: The engine "node" is incompatible with this module. Expected version "^6.9.0 || ^8.9.0 || ^10.13.0". Got "11.6.0"
warning ghost@2.13.1: The engine "cli" appears to be invalid.
error Found incompatible module

    at ChildProcess.exithandler (child_process.js:294:12)
    at ChildProcess.emit (events.js:188:13)
    at maybeClose (internal/child_process.js:978:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
```

running yarn v1.13.0 on macOS

`Error: Command failed: yarn` looks strange

**Comment by kandros** [comment]
using node 10 solved the issue
