### ISSUE TITLE
Errors from SDL Converted Schema in Nexus

### ISSUE THREAD

**Issue by jblevins1991** [prisma/nexus#85]
I have a repository I have been using to learn nexus at https://github.com/jblevins1991/Nexus-Example/tree/converter. On the converter branch I took my schema from the generated folder that is created by the prisma generate command and used the SDL Converter on it. Here is the link for that converted schema https://github.com/jblevins1991/Nexus-Example/blob/converter/src/schema/schema.js.

In my index file in the schema folder I import my schema and use it in the makeSchema function. When I run the application I get the following error from nexus's index.js file.

```
TypeError: schema.getTypeMap is not a function
    at forEachField (/home/developer/Documents/nexus-example/src/node_modules/graphql-extensions/lib/index.js:157:26)
    at Object.enableGraphQLExtensions (/home/developer/Documents/nexus-example/src/node_modules/graphql-extensions/lib/index.js:106:5)
    at doRunQuery (/home/developer/Documents/nexus-example/src/node_modules/apollo-server-core/dist/runQuery.js:67:30)
    at /home/developer/Documents/nexus-example/src/node_modules/apollo-server-core/dist/runQuery.js:21:56
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: Expected { _extensionsEnabled: true } to be a GraphQL schema.
    at invariant (/home/developer/Documents/nexus-example/src/node_modules/graphql/jsutils/invariant.js:19:11)
    at assertSchema (/home/developer/Documents/nexus-example/src/node_modules/graphql/type/schema.js:38:46)
    at validateSchema (/home/developer/Documents/nexus-example/src/node_modules/graphql/type/validate.js:51:28)
    at assertValidSchema (/home/developer/Documents/nexus-example/src/node_modules/graphql/type/validate.js:75:16)
    at Object.validate (/home/developer/Documents/nexus-example/src/node_modules/graphql/validation/validate.js:55:35)
    at doRunQuery (/home/developer/Documents/nexus-example/src/node_modules/apollo-server-core/dist/runQuery.js:111:42)
    at /home/developer/Documents/nexus-example/src/node_modules/apollo-server-core/dist/runQuery.js:21:56
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by jblevins1991** [comment]
Nevermind, somehow I accidentally deleted the module.exports line form index.js in schema directory.
